import React, { useState } from "react";
import { elementToPng } from "../utils/exportToImage";
import { createPdfPage } from "../utils/exportToPdf";

interface Props {
  chartRefs: Record<string, HTMLElement | null>;
  provinceName: string;
}

const DownloadReportButton: React.FC<Props> = ({ chartRefs, provinceName }) => {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    setLoading(true);

    const images = [];

    for (const [label, element] of Object.entries(chartRefs)) {
      if (!element) continue;
      const img = await elementToPng(element);
      images.push({ label, dataUrl: img });
    }

    const pdf = createPdfPage({
      header: `EnergyDashboard Report – ${provinceName}`,
      footer: `Generated by EnergyDashboard · ${new Date().toLocaleString()}`,
      images,
    });

    pdf.save(`EnergyDashboard_${provinceName}.pdf`);
    setLoading(false);
  }

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="download-btn"
    >
      {loading ? "Preparing report..." : "Download Report"}
    </button>
  );
};

export default DownloadReportButton;
